<?php

// PHP Data Model definition file

// WARNING - WARNING - WARNING
// DO NOT EDIT THIS FILE (unless you know what you are doing)
//
// If you use supply a datamodel.xxxx.xml file with your module
// the this file WILL BE overwritten by the compilation of the
// module (during the setup) if the datamodel.xxxx.xml file
// contains the definition of new classes or menus.
//
// The recommended way to define new classes (for iTop 2.0) is via the XML definition.
// This file remains in the module's template only for the cases where there is:
// - either no new class or menu defined in the XML file
// - or no XML file at all supplied by the module

class RiskUIExt implements iPageUIExtension
{
	
    
    protected $MODULE_PATH = '../env-production/suntech-warehouse-mgmt';
    
    
    
    /**
	 * Add content to the North pane
	 * @param iTopWebPage $oPage The page to insert stuff into.
	 * @return string The HTML content to add into the page
	 */
	public function GetNorthPaneHtml(iTopWebPage $oPage)
    {
        
        
        //$oPage->add_linked_stylesheet($this->MODULE_PATH.'/css/kamadatepicker.css');

        $text = "";
        
        return $text;
    }
    
	/**
	 * Add content to the South pane
	 * @param iTopWebPage $oPage The page to insert stuff into.
	 * @return string The HTML content to add into the page
	 */
	public function GetSouthPaneHtml(iTopWebPage $oPage)
    {
    	

    	$sClass = utils::ReadParam('class', '');
    	$operation = utils::ReadParam('operation', '');
    	


    	if ($sClass=='Risk')
    	{
    		$oPage->add_ready_script(
<<<EOF
    $(document).ready(function(){
        
		$('#2_priority').prop('disabled',true);
					
	
	});
EOF
    	);
    	}


        $text = "";
        return $text;
        
    }
	
    /**
	 * Add content to the "admin banner"
	 * @param iTopWebPage $oPage The page to insert stuff into.
	 * @return string The HTML content to add into the page
	 */
	public function GetBannerHtml(iTopWebPage $oPage)
    {
        $text = "";
        
        
        
        
        return $text;
    }
    
    
}