						<?php
//
// File generated by ... on the 2018-03-31T22:29:17+0200
// Please do not edit manually
//

/**
 * Classes and menus for suntech-device (version 1.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */


/**
 * Persistent classes for a CMDB
 *
 * @copyright   Copyright (C) 2010-2017 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
class UserHardware extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable,structure',
			'key_type' => 'autoincrement',
			'name_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('contact_id'),
			'db_table' => 'user_hardware',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeInteger("contact_id", array("allowed_values"=>null, "sql"=>'contact_id', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("serial_number", array("allowed_values"=>null, "sql"=>'serial_number', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("mac_id", array("allowed_values"=>null, "sql"=>'mac_id', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("description", array("allowed_values"=>null, "sql"=>'description', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("datetime", array("allowed_values"=>null, "sql"=>'datetime', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("hardware_type", array("allowed_values"=>null, "sql"=>'hardware_type', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("username", array("allowed_values"=>null, "sql"=>'username', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("status", array("allowed_values"=>null, "sql"=>'status', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("confirmed", array("allowed_values"=>null, "sql"=>'confirmed', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'contact_id',
  1 => 'serial_number',
  2 => 'mac_id',
  3 => 'description',
  4 => 'datetime',
  5 => 'hardware_type',
  6 => 'username',
  7 => 'status',
  8 => 'confirmed',
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'contact_id',
  1 => 'serial_number',
  2 => 'mac_id',
  3 => 'description',
  4 => 'datetime',
  5 => 'hardware_type',
  6 => 'username',
  7 => 'status',
  8 => 'confirmed',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'contact_id',
  1 => 'serial_number',
  2 => 'mac_id',
  3 => 'description',
  4 => 'datetime',
  5 => 'hardware_type',
  6 => 'username',
  7 => 'status',
  8 => 'confirmed',
));

	}


}

/**
 * Persistent classes for a CMDB
 *
 * @copyright   Copyright (C) 2010-2017 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
class UserSoftware extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable,structure',
			'key_type' => 'autoincrement',
			'name_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('contact_id'),
			'db_table' => 'user_software',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeInteger("contact_id", array("allowed_values"=>null, "sql"=>'contact_id', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("username", array("allowed_values"=>null, "sql"=>'username', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("software_title", array("allowed_values"=>null, "sql"=>'software_title', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("description", array("allowed_values"=>null, "sql"=>'description', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("datetime", array("allowed_values"=>null, "sql"=>'datetime', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("status", array("allowed_values"=>null, "sql"=>'status', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("confirmed", array("allowed_values"=>null, "sql"=>'confirmed', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'contact_id',
  1 => 'username',
  2 => 'software_type',
  3 => 'description',
  4 => 'datetime',
  5 => 'status',
  6 => 'confirmed',
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'contact_id',
  1 => 'username',
  2 => 'software_type',
  3 => 'description',
  4 => 'datetime',
  5 => 'status',
  6 => 'confirmed',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'contact_id',
  1 => 'username',
  2 => 'software_type',
  3 => 'description',
  4 => 'datetime',
  5 => 'status',
  6 => 'confirmed',
));

	}


}